language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
install: "python setup.py"
# command to run tests
script: python -m unittest discover -s test -p 'test*.py'
